#!/bin/bash
# Verificar se existe arquivos duplicados
# Requer zenity (Display graphical dialog boxes) instalado
# Teste executado com Bash no Debian

script="$(basename $0)"
today=$(date +%Y-%m-%d)
result=""

# Log
echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"

# Checar argumento
echo "Input: $1"
if [[ "$1" = "" ]]; then
    echo "Empty argument!" >> /tmp/"log-$script-$today"
    zenity --info --text="Select only one file!"
    exit 0
fi

# Procurar extensão
arg="$(basename $1)"
size=${#arg}
count=$size
while [[ $count -ge 0 ]]; do
    if [[ ${arg:((--count)):1} = '.' ]]; then
        break;
    fi
done

# Dados
rootDir=$PWD
name="$arg"
ext=""
if [[ $count -ge 0 ]]; then
    name="${arg:0:count}"
    ext="${arg:count:size-count}"
fi
out="$rootDir/$script-result-$today"

# Confirmando ação
zenity --question \
--title="Script" \
--text="Execute: $script\nSearch: $name$ext" \
--ok-label="Yes" \
--cancel-label="No"
temp=$?

if [[ $temp -eq 1 ]]; then
    echo "Closed by user!" >> /tmp/"log-$script-$today"
    exit 0
fi

# Pesquisar
echo "$script ..."
echo "Processing search. Wait ..."
started="Started [ $(date '+%Y-%m-%d %H:%M:%S') ]."

echo "Duplicates:"
# [find md5sum]
# 1607cafdb47fa1db1dabdac36d64f4cb  ./test.txt
# [sort | uniq | cut]       =>      ./test.txt (result)
result=($(find $rootDir -type f -iname "*$name*$ext" -exec md5sum {} \; | sort | uniq --all-repeated=separate -w 33 | cut -c 35-))
result=($(echo "${result[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

# Output
touch $out
echo "# Filename : \"$name\"" > $out
echo "# Extension: \"$ext\"" >> $out
echo "# Directory: $rootDir" >> $out
echo "# Possibly Duplicate Files" >> $out
for i in ${result[@]}; do
    echo $i
    echo $i >> $out
done
echo "" >> $out
echo $started >> $out
echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> $out

# Sair
zenity --info --text="Check: $out"
echo "$script ... ok" >> /tmp/"log-$script-$today"
echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
exit 0