#!/bin/bash
# Simples script para listar arquivos e relacionar com diretórios, salvando em CSV.
# Requer: Zenity
# 2023

# Argumentos de entrada
arg="$@"
script=$(basename $0)
today=$(date +%Y-%m-%d)
now=$(date +%Y-%m-%d-%H:%M:%S)
output="list_$now.csv"

# Checar argumento
if [[ "$arg" = "" ]]; then
    echo "Empty argument!" >> /tmp/"log-$script-$today"
    zenity --info --text="Select Files!"
    exit 0
fi

# Confirmando ação
zenity --question \
--title="Script" \
--text="Execute: $script \nProcess can take time!" \
--ok-label="Yes" \
--cancel-label="No"
temp=$?

if [[ $temp -eq 1 ]]; then
      exit 0
fi

# Escrevendo arquivo de log
echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"

# CSV
delimiter=";"
temp="/tmp/$script-bkp"
echo -n "" > $temp

# Percorrendo os argumentos de entrada
arr=($arg)
for path in "${arr[@]}"; do
    if [[ -d "$path" ]]; then
        for i in $(find "$path" -print); do
            if [[ -d "$i" ]]; then
                for j in $(ls -a $i); do
                    if [[ -f "$i/$j" ]]; then
                        file=($(ls -la --time-style=full-iso "$i/$j"))
                        echo ${file[5]} $j "..."
                        echo ${file[5]}$delimiter$j$delimiter$i >> $temp
                    fi
                done
            fi
        done
    else
        echo "Error when reading: $path" >> /tmp/"log-$script-$today"
        zenity --info --title="Error!" --text="$path"     
    fi
done

# Organizar e salvar
echo "time$delimiter""files$delimiter""directories" > $output
sort $temp >> $output
echo "Save in: $output"

echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
exit 0