#!/bin/bash
# Formata arquivo CPP e HPP usando Artistic Style
# Requer zenity e astyle
# 2021

# argumentos de entrada
arg="$@"
local=$(dirname $0)
script=$(basename $0)
today=$(date +%Y-%m-%d)

# Checar argumento
if [[ "$arg" = "" ]]; then
    echo "Empty argument!" >> /tmp/"log-$script-$today"
    zenity --info --text="Select Files!"
    exit 0
fi

# detalhes iniciais
ext_original=(".CPP" ".HPP")

# Confirmando ação
zenity --question \
--title="Script" \
--text="Execute: $script" \
--ok-label="Yes" \
--cancel-label="No"
temp=$?

if [[ $temp -eq 1 ]]; then
      exit 0
fi

# Escrevendo arquivo de log
echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"

# Percorrendo os argumentos de entrada
for arg
do
    size=${#arg}
    count=$size

    # Procurando extensão
    while [[ $count -ge 0 ]]; do
        if [[ ${arg:((--count)):1} = '.' ]]; then
            break;
        fi
    done

    # Checar extensão
    ext_temp=$(echo "${arg:count:size - count}" | tr '[:lower:]' '[:upper:]')
    if [[ $ext_temp != ${ext_original[0]} && $ext_temp != ${ext_original[1]} ]]; then
        echo "Invalid image file!" >> /tmp/"log-$script-$today"
        zenity --error --text="Invalid image file!"        
        continue
    fi

    # Artist Style
    echo "Format $arg ..." >> /tmp/"log-$script-$today"
    $(astyle --options=$local/style_cpp.astylerc "$arg")

done

echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
exit 0
