#!/bin/bash
# Converte arquivo imagem para PDF
# Requer Zenity e ImageMagick

# argumentos de entrada
arg="$@"        
elements="$#"

today=$(date +%Y-%m-%d)
ext_array=("PNG" "png" "JPG" "jpg" "svg" "SVG")

# Confirmando ação
gdialog --title "Script" --center --stdout --yesno \
"Execute: img2pdf" \
100 100

# Escrevendo arquivo de log
echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-img2pdf-$today"

# Checar argumento
if [[ "$arg" = "" ]]; then
    echo "Empty argument!" >> /tmp/"log-img2pdf-$today"
    gdialog --msgbox "Select Files!"
    exit 0
fi

# Percorrendo os argumentos de entrada
temp=""
for arg
do
    # argumento
    size=${#arg}
    count=$size

    # Procurando extensão
    while [[ $count -ge 0 ]]; do
        if [[ ${arg:((--count)):1} = '.' ]]; then
            break;
        fi
    done

    # Checar extensão
    ext_temp="${arg:count:size - count}"
    name="PDF"  # padrão para mais de um arquivo
    for ext in ${ext_array[@]}; do
        if [[ $ext_temp == ".$ext" ]]; then
            echo "Image file: $arg OK" >> /tmp/"log-img2pdf-$today"
            temp="$temp $arg"
            # nome do arquivo
            if [[ $elements -eq 1 ]]; then
                last=$count
                while [[ $count -ge 0 ]]; do
                    if [[ ${arg:((--count)):1} = '/' ]]; then
                        break;
                    fi
                done
                name="${arg:count + 1:last - count - 1}" 
            fi
            break
        fi
    done
done

# Inserir Data
output="$name-$(date '+%Y-%m-%d_%H:%M:%S').pdf"
if [[ -f $output ]]; then
    echo "Error: '$output' already exists!" >> /tmp/"log-img2pdf-$today"
    gdialog --msgbox "Error: '$output' already exists!"
else
    echo "Converting..." >> /tmp/"log-img2pdf-$today"
    $(convert $temp $output)
    echo "Output: $output" >> /tmp/"log-img2pdf-$today"
fi

echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-img2pdf-$today"
exit 0