#!/bin/bash
# Converte arquivo imagem SVG para PDF
# Requer Zenity e Inkscape
# 2021

# argumentos de entrada
arg="$@"
script=$(basename $0)
today=$(date +%Y-%m-%d)

# Checar argumento
if [[ "$arg" = "" ]]; then
    echo "Empty argument!" >> /tmp/"log-$script-$today"
    zenity --info --text="Select Files!"
    exit 0
fi

# detalhes iniciais
ext_original=(".SVG")
ext_output="pdf"
extra=""

# Confirmando ação
zenity --question \
--title="Script" \
--text="Execute: $script" \
--ok-label="Yes" \
--cancel-label="No"
temp=$?

if [[ $temp -eq 1 ]]; then
      exit 0
fi

# Escrevendo arquivo de log
echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"

# Percorrendo os argumentos de entrada
for arg
do
    size=${#arg}
    count=$size
    echo "Convert: $arg" >> /tmp/"log-$script-$today"

    # Procurando extensão
    while [[ $count -ge 0 ]]; do
        if [[ ${arg:((--count)):1} = '.' ]]; then
            break;
        fi
    done

    # Checar extensão
    ext_temp=$(echo "${arg:count:size - count}" | tr '[:lower:]' '[:upper:]')
    if [[ $ext_temp != ${ext_original[0]} && $ext_temp != ${ext_original[1]} ]]; then
        echo "Invalid image file!" >> /tmp/"log-$script-$today"
        zenity --error --text="Invalid image file!"        
        continue
    fi

    # Inserir Data
    temp="${arg:0:$count}.$ext_output"
    if [[ -f $temp ]]; then
        echo "Error: '$temp' already exists!" >> /tmp/"log-$script-$today"
        zenity --error --text="Error: '$temp' already exists!"
    else
        echo "Converting..." >> /tmp/"log-$script-$today"
        $(inkscape -z "$arg" --export-dpi=150 --export-area-page --export-pdf="$temp")
        # $(flatpak run org.inkscape.Inkscape -z "$arg" --export-dpi=150 --export-area-page --export-pdf="$temp")        
        echo "New: $temp" >> /tmp/"log-$script-$today"
    fi
done

echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
exit 0